[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
agent_payrails = "89z9gaDA7THtpbJ8WXS56mfRjxHHCWLcvCDZXrLU9qGk"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
